pipeline
{
  agent any
  tools
  {
    maven 'Maven'
    jdk 'jdk-11'
   }
   stages{
    stage('Build') {
      steps {
        sh 'mvn build'
        echo 'Building'
      }
   }
   stage('Test') {
      steps  {
          sh 'mvn test'
          echo 'Testing'
       }
    }
  }
}
