pipeline
{
 agent {
    docker {
      image 'maven:3.6.3-jdk-11'
      args '-v /root/.m2:/root/.m2'
    }
 }
   stages{
    stage('Build') {
      steps {
        sh 'mvn -f PipelineCC/pom.xml compile'
        echo 'Building'
      }
   }
   stage('Test') {
      steps  {
          sh 'mvn -f PipelineCC/pom.xml  test'
          echo 'Testing'
       }
    }
    
    stage("Build & SonarQube analysis") {
            agent any
            steps {
              withSonarQubeEnv('Sonar-Service2') {
                sh 'java -version'
                sh 'mvn clean package sonar:sonar'
              }
            }
          }
     stage('Deploy to artifactory'){
        steps{
        rtUpload(
         serverId : 'Artifactory_server',
         spec :'''{
           "files" :[
           {
           "pattern":"target/*.jar",
           "target":"art-doc-devo-loc"
           }
           ]
         }''',
         
      )
      }
     }
  }
}
